name: 01 - Building Blocks
on:
  workflow_dispatch: 

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "hello World"

  say-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: success
        run: |
          echo "i will succeed"
          exit 0
      - name: say goodbye
        run: echo "goodbye World"
