name: Workflow Runners

on:
  push:
    branches:
      - main

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show Ubuntu runner
        run: |
          echo "This runner is running on Ubuntu OS"
          echo "The runner OS is ${{ runner.os }}"

  windows-echo:
    runs-on: windows-latest
    steps:
      - name: Show Windows runner
        run: |
          echo "This runner is running on Windows OS"
          echo "The runner OS is ${{ runner.os }}"
